"""fw_harness.py — scaffolded by ``/fireweave:initialise`` (PYTHON surface).

The "promote, not wrap" harness (D26): the RUNNING ENVIRONMENT — resolved by
NAME, not a bare boolean — selects the branch via ``FW_ENV_PROFILES``.
  dev  -> in-memory OpenFeature provider + OTel console exporter
  prod -> DEFERRED for the python surface (Phase 1c): the connected PostHog
          OpenFeature provider + direct OTLP + boot beacon are not built yet, so
          this harness scaffolds DEV-only console wiring and NEVER fakes a prod
          branch (``verify_prod_path`` skips python as a recorded gap, not a pass).

``init_fw_harness()`` MUST be called as the FIRST statement in the app entrypoint
(top of ``__main__`` / the ASGI/WSGI app factory) so the provider + telemetry are
live before any flag read. ``is_prod()`` is retained as the tier fallback + the
token a future python ``verify_prod_path`` greps for.
"""

from __future__ import annotations

import os
import warnings
from typing import Mapping

from openfeature import api

from .fw_providers import make_connected_vendor_provider, make_dev_provider
# Plain import — USED below (passed nowhere yet, but referenced) so the stamp
# tree is not stripped. The python deploy SDK (Phase 1b) will send these.
from .fw_tracker import FW_STAMPS

# Surface participation (surface-ID routing) — dev-only tracking on this branch.
# fw-server mints one ``sfc_<ULID>`` per surface and ``/fireweave:initialise``
# RECORDS it here (Step 3f, ``fw repo declare-surfaces``) -- never invent one; its
# ``stamps`` are THIS surface's ``FW_STAMPS``. The python deploy SDK (Phase 1b)
# will send ``FW_SURFACES`` on the boot beacon (alongside the deduped ``stamps``
# union). Tracked but NOT transmitted yet — no prod-path work on this branch.
FW_SURFACES: list[dict[str, object]] = [{"surface_id": "sfc_REPLACE_ON_INIT", "stamps": FW_STAMPS}]

# env -> tier profile — regenerated from FireWeave ``list_project_environments``.
# Keep in sync with ``.fireweave/project.json`` ``rolloutReady.environments``.
# ``FW_DEFAULT_ENV`` is the project's ``defaultEnvironment`` — the row used when
# nothing is set at runtime. ``/fireweave:initialise --reinit`` regenerates this.
FW_DEFAULT_ENV = "development"
FW_ENV_PROFILES: dict[str, str] = {
    "development": "dev",
    "staging": "prod",
    "production": "prod",
}


# ── Environment source — GENERATED by ``/fireweave:initialise`` ──────────────
# FireWeave reads THIS project's OWN environment signal — you do NOT need to add
# a FireWeave-specific ``FW_ENV``. ``/fireweave:initialise`` asks how this repo /
# CI determines its live environment and generates ``_read_env_signal`` below to
# read YOUR var (``APP_ENV`` / ``ENVIRONMENT`` / a framework setting / a platform
# var). ``FW_ENV`` is retained ONLY as an optional override. Regenerated on
# ``--reinit`` — edit through the skill, not by hand.
# fw:env-source
def _read_env_signal(env: Mapping[str, str]) -> str | None:
    # Default before init tailors it to your app/platform: common env vars, then
    # the optional FW_ENV override. ``/fireweave:initialise`` replaces the first
    # read per your answer.
    return env.get("APP_ENV") or env.get("ENVIRONMENT") or env.get("ENV") or env.get("FW_ENV")


# Map a raw signal value -> a FireWeave environment NAME (a key of
# FW_ENV_PROFILES). initialise fills this only when your values differ from the
# FireWeave names (e.g. {"prod": "production"}). Empty = identity mapping.
FW_ENV_ALIASES: dict[str, str] = {}
# ─────────────────────────────────────────────────────────────────────────────


def resolve_fw_env_name(env: Mapping[str, str]) -> str:
    """Resolve the running environment NAME from the project's own signal."""
    raw = (_read_env_signal(env) or FW_DEFAULT_ENV).strip()
    return FW_ENV_ALIASES.get(raw, raw)


def _resolve_fw_tier(env: Mapping[str, str]) -> str:
    return FW_ENV_PROFILES.get(resolve_fw_env_name(env), "")


def is_prod(env: Mapping[str, str] | None = None) -> bool:
    """Retained tier probe + the token ``verify_prod_path`` greps for."""
    env = os.environ if env is None else env
    return _resolve_fw_tier(env) == "prod"


_ready = False


def init_fw_harness() -> None:
    """Idempotent boot — call FIRST in the app entrypoint, before any flag read."""
    global _ready
    if _ready:
        return
    _ready = True

    env = os.environ
    fw_env_name = resolve_fw_env_name(env)
    profile = FW_ENV_PROFILES.get(fw_env_name)
    # Unknown environment is NOT silently folded into dev/prod — fall back to the
    # is_prod() tier probe and WARN so the operator adds an explicit profile row.
    prod = (profile == "prod") if profile is not None else is_prod(env)
    if profile is None:
        warnings.warn(
            f"[fireweave] environment '{fw_env_name}' has no FW_ENV_PROFILES entry; "
            f"classified as '{'prod' if prod else 'dev'}' via is_prod() fallback. "
            "Run /fireweave:initialise --reinit or add it to FW_ENV_PROFILES.",
            stacklevel=2,
        )

    if prod:
        # PROD is DEFERRED for the python surface (Phase 1c): no connected PostHog
        # OpenFeature provider / direct OTLP / boot beacon yet. Scaffold DEV-only
        # console wiring so the app still runs, and NEVER fake a prod branch.
        warnings.warn(
            "[fireweave] python prod rollout is deferred — running DEV-only console "
            "wiring. Build and test locally; prod ramp support lands in a later feature.",
            stacklevel=2,
        )
        # Touch the deferred prod provider factory so it is not dead code; it
        # raises if actually invoked (see fw_providers.make_connected_vendor_provider).
        _ = make_connected_vendor_provider

    # DEV wiring (used for every tier until python prod support ships):
    api.set_provider(make_dev_provider())
    _init_console_telemetry("fireweave-app")

    # Boot beacon: DEFERRED (Phase 1b). The python deploy SDK provides
    # ``init_fw_attestation``; until then the stamp tree and its per-surface
    # participation are tracked but not sent.
    _ = FW_STAMPS
    _ = FW_SURFACES


def _init_console_telemetry(service_name: str) -> None:
    """DEV telemetry: OTel console span exporter (no vendor egress)."""
    from opentelemetry import trace
    from opentelemetry.sdk.resources import Resource
    from opentelemetry.sdk.trace import TracerProvider
    from opentelemetry.sdk.trace.export import ConsoleSpanExporter, SimpleSpanProcessor

    provider = TracerProvider(resource=Resource.create({"service.name": service_name}))
    provider.add_span_processor(SimpleSpanProcessor(ConsoleSpanExporter()))
    trace.set_tracer_provider(provider)


def fw_flag(key: str, default: bool) -> bool:
    """Flag-eval facade. Call after ``init_fw_harness()``. Anchor each call site
    with ``# @fireweave-flag <key>``."""
    return api.get_client().get_boolean_value(key, default)
