// FwProviders.swift — scaffolded by `/fireweave:initialise` (SWIFT surface).
//
// `makeDevProvider()` brings the SDK up in LOCAL mode — an in-process seeded
// map, no network, no credentials — through `initFireweave()`, the same single
// entry point a prod branch will call once swift is prod-capable. It is the
// ONLY branch `FwHarness.initFwHarness()` ever takes today.
//
// `makeConnectedVendorProvider()` is a DELIBERATE stub that THROWS rather than
// silently degrading. Swift is classified DEV-ONLY in FireWeave's surface
// registry: the SDK is conformance-green with a working remote adapter, but its
// release mechanism is tag-only — no package-registry publish path exists and no
// tag has been cut — so there is no installable artifact a scaffolded prod
// branch could depend on. A stub that threw is recoverable; a branch that looked
// connected while serving nothing is not. Replace the body with a real
// remote-mode `initFireweave` call (mirroring ts-server/python/java) once a
// real tagged release exists AND `SURFACE_REGISTRY.swift.prodProviderVendors`
// is flipped to `FIREWEAVE_ONLY`. Conformance passing is necessary but not
// sufficient on its own. Two guards pin the refusal — keep them in step.
//
// `syncFireweaveUser()` is the OTHER half of targeting — named (and shaped)
// after the WEB surface's identical helper rather than python/java's plain
// `registerFwTarget`: swift shares web's async-prefetch/sync-read architecture,
// so registering a durable fact is only useful together with a cache re-prefetch
// (`FireweaveClient.identify`); python and java evaluate live per call and have
// no cache to go stale. Rules match on two kinds of property and you need both:
//
//   - DURABLE — registered here, once per login / device provisioning: plan,
//     beta membership, region, device model. Stored server-side, so rules keep
//     matching without the app resending anything.
//   - PER-REQUEST — the per-call evaluation context. Overrides the registered
//     value for that one call.
//
// A rule targeting a property that is never registered AND never sent matches
// nobody, silently. Register the durable facts at sign-in.
//
// Observability is NOT wired here. FireWeave does not take responsibility for
// wiring an observability SDK into an app that has not chosen one.

import Fireweave
import Foundation

public enum FwProviders {

  // ── Environment-keyed tier model (D26) — GENERATED by `/fireweave:initialise` ──
  // This lives here, not in FwHarness.swift, so the file you review stays small.
  // `staging` is a FIRST-CLASS prod-tier environment — never folded into dev.

  /// env name -> tier profile — regenerated from FireWeave
  /// `list_project_environments`. Keep in sync with `.fireweave/project.json`
  /// `rolloutReady.environments`. `fwDefaultEnv` is the project's
  /// `defaultEnvironment` — the row used when nothing is set at runtime.
  /// `/fireweave:initialise --reinit` regenerates this map.
  public static let FW_DEFAULT_ENV = "development"

  static let FW_ENV_PROFILES: [String: String] = [
    "development": "dev",
    "staging": "prod",
    "production": "prod",
  ]

  // ── Environment source — GENERATED by `/fireweave:initialise` ──────────────
  // FireWeave reads THIS project's OWN environment signal — you do NOT need a
  // FireWeave-specific `FW_ENV`. `/fireweave:initialise` asks how this app
  // determines its live environment and generates `readEnvSignal` below to read
  // YOUR signal (an Info.plist key, a build configuration, an `APP_ENV` var).
  // `FW_ENV` is retained ONLY as an optional last-resort override. Regenerated
  // on `--reinit` — edit via the skill.
  // fw:env-source
  static func readEnvSignal(_ env: [String: String]) -> String? {
    // Info.plist FIRST — this is the only one of these that exists in a SHIPPED
    // iOS build. A process environment is populated by an Xcode scheme, so it is
    // present in the simulator and absent on a device; reading it first would
    // resolve a TestFlight/App Store build to `development` and quietly bring
    // the SDK up in local mode, serving every control point its default with a
    // clean log. Set `FWEnvironment` in Info.plist from your build
    // configuration (`$(FW_ENVIRONMENT)` in an xcconfig) so each build carries
    // its own tier. Env vars remain a dev/simulator override.
    infoPlistString("FWEnvironment")
      ?? env["APP_ENV"] ?? env["ENVIRONMENT"] ?? env["ENV"] ?? env["FW_ENV"]
  }

  /// Read a non-empty string from the app bundle's Info.plist.
  static func infoPlistString(_ key: String) -> String? {
    guard
      let raw = Bundle.main.object(forInfoDictionaryKey: key) as? String
    else { return nil }
    let trimmed = raw.trimmingCharacters(in: .whitespaces)
    return trimmed.isEmpty ? nil : trimmed
  }

  /// Raw signal value -> FireWeave environment NAME (a key of
  /// `FW_ENV_PROFILES`). initialise fills this only when your values differ
  /// from the FireWeave names (e.g. ["prod": "production"]). Empty = identity.
  static let FW_ENV_ALIASES: [String: String] = [:]
  // ───────────────────────────────────────────────────────────────────────────

  /// Resolve the running environment NAME from the project's own signal.
  public static func resolveFwEnvName(
    _ env: [String: String] = ProcessInfo.processInfo.environment
  ) -> String {
    let raw = (readEnvSignal(env) ?? FW_DEFAULT_ENV).trimmingCharacters(in: .whitespaces)
    let name = raw.isEmpty ? FW_DEFAULT_ENV : raw
    return FW_ENV_ALIASES[name] ?? name
  }

  /// Is this build a prod-tier environment? The tier decision `FwHarness`
  /// branches on, and the token `verify_prod_path` greps for.
  ///
  /// An UNKNOWN environment is never silently folded into dev or prod — it
  /// warns, so the operator adds an explicit row rather than discovering the
  /// classification from behaviour.
  public static func isProd(
    _ env: [String: String] = ProcessInfo.processInfo.environment
  ) -> Bool {
    let name = resolveFwEnvName(env)
    if let profile = FW_ENV_PROFILES[name] { return profile == "prod" }
    FileHandle.standardError.write(
      Data(
        ("[fireweave] environment '\(name)' has no FW_ENV_PROFILES entry; "
          + "classified as 'dev'. Run /fireweave:initialise --reinit or add it "
          + "to FW_ENV_PROFILES.\n").utf8))
    return false
  }


  /// PERSISTED device identity — the targeting key before sign-in.
  ///
  /// spec/control-points.md forbids the SDK from inventing a targeting key, and
  /// it is right to: a CONSTANT key hashes every caller into one bucket, so a
  /// percentage ramp serves either everybody or nobody while looking perfectly
  /// healthy. The HARNESS is the correct place to solve it — identity is the
  /// app's concern, and only the app knows where it may persist one.
  ///
  /// Minted once into `UserDefaults` so the same device lands in the same
  /// bucket across launches, which is what makes a 10% ramp mean 10% of
  /// devices. At sign-in, `syncFireweaveUser()` re-prefetches under the real
  /// user id. Mirrors the web surface, since swift shares its
  /// async-prefetch/sync-read shape.
  ///
  /// UserDefaults rather than Keychain deliberately: this id is not a secret
  /// and must not survive an app uninstall — a Keychain-persisted id would
  /// follow a reinstall and keep a "new" device in its old bucket.
  private static let deviceIdDefaultsKey = "fireweave.device-id"

  private static func resolveDeviceTargetingKey() -> String {
    let defaults = UserDefaults.standard
    if let existing = defaults.string(forKey: deviceIdDefaultsKey), !existing.isEmpty {
      return existing
    }
    let minted = "dev_\(UUID().uuidString)"
    defaults.set(minted, forKey: deviceIdDefaultsKey)
    return minted
  }

  private static let stateLock = NSLock()
  private static var fwClient: FireweaveClient?

  /// DEV: the SDK's local mode — the only wired branch until swift is prod-capable.
  ///
  /// Call-site / manifest defaults stay `false` (RAMP-1). To dogfood a control
  /// point ON locally, seed it here — never `fwFlag(key, default: true)` (that
  /// same `true` is the prod fallback when the key is missing from the backend):
  ///
  ///     InitFireweaveLocalOptions(controlPoints: ["<feature-slug>": true])
  @discardableResult
  public static func makeDevProvider() async throws -> FireweaveClient {
    let client = try await initFireweave(
      .local(
        InitFireweaveLocalOptions(
          controlPoints: [:],
          context: EvaluationContext(targetingKey: resolveDeviceTargetingKey()))))
    stateLock.withLock { fwClient = client }
    return client
  }

  /// PROD: NOT wired — see this file's header. Throws instead of pretending to
  /// connect, so a future edit that reaches it before a real release exists
  /// fails loudly rather than serving every default.
  public static func makeConnectedVendorProvider() async throws -> FireweaveClient {
    // Credentials are BUILD-BAKED, like the web surface: an iOS app has no
    // server-side env to read at launch. `initialise` writes these Info.plist
    // keys from your xcconfig; the SDK itself reads no configuration anywhere
    // (spec/modes.md), so this file is the seam where they become options.
    guard let apiKey = infoPlistString("FWProjectApiKey"), !apiKey.isEmpty else {
      throw FireweaveError(
        kind: .configuration,
        message: "[fireweave] FWProjectApiKey missing from Info.plist — a "
          + "prod-tier build must fail loudly rather than degrade to local "
          + "evaluation, which serves every control point its default.")
    }
    guard let apiUrl = infoPlistString("FWApiUrl"), !apiUrl.isEmpty else {
      throw FireweaveError(
        kind: .configuration,
        message: "[fireweave] FWApiUrl missing from Info.plist — see "
          + "FWProjectApiKey above.")
    }
    let normalised =
      apiUrl.hasSuffix("/") ? String(apiUrl.dropLast()) : apiUrl
    let client = try await initFireweave(
      .remote(
        InitFireweaveRemoteOptions(
          apiKey: apiKey,
          apiUrl: normalised,
          // A self-hosted fw-server must list its own host explicitly, or the
          // SDK rejects apiUrl against the canonical allowlist and init fails
          // with a bare Configuration error naming nothing.
          allowedHosts: allowedHostsFor(normalised),
          context: EvaluationContext(targetingKey: resolveDeviceTargetingKey()))))
    stateLock.withLock { fwClient = client }
    return client
  }

  /// Derive the SSRF allowlist from the configured URL so a customer-run
  /// fw-server on any hostname stays reachable.
  static func allowedHostsFor(_ apiUrl: String) -> [String] {
    guard let host = URLComponents(string: apiUrl)?.host, !host.isEmpty else {
      return ["localhost", "127.0.0.1"]
    }
    return [host, "localhost", "127.0.0.1"]
  }

  /// Sign-in hook: ONE call (`client.identify`) that registers the user's
  /// durable targeting properties AND re-prefetches the decision cache under the
  /// new id, so a later percentage ramp buckets on a stable id:
  ///
  ///     await syncFireweaveUser("user_42", properties: ["plan": .string("pro")])
  ///
  /// Resolves rather than throwing — it runs in sign-in paths, where a targeting
  /// concern must not break authentication. Before `initFwHarness()` finishes
  /// there is no client yet, so this resolves `ok: false` rather than pretending
  /// to have registered anything.
  @discardableResult
  public static func syncFireweaveUser(
    _ targetingKey: String,
    properties: [String: JSONValue]? = nil,
    kind: TargetKind = .user
  ) async -> RegisterTargetResult {
    guard let client = currentFwClient() else {
      return .failure(FireweaveError(kind: .notReady))
    }
    return await client.identify(
      targetingKey,
      options: RegisterTargetOptions(kind: kind, properties: properties))
  }

  /// The client `initFwHarness()` brought up — call-sites read control points
  /// through this.
  public static func getFwClient() -> FireweaveClient {
    guard let client = currentFwClient() else {
      fatalError(
        "[fireweave] getFwClient() called before initFwHarness() finished — await it first.")
    }
    return client
  }

  private static func currentFwClient() -> FireweaveClient? {
    stateLock.withLock { fwClient }
  }
}
