/**
 * fw-harness.ts — scaffolded by `/fireweave:initialise` (TS-server surface).
 *
 * The "promote, not wrap" harness (D26): BOTH branches are present and the
 * RUNNING ENVIRONMENT — resolved by NAME, not a bare boolean — selects which one
 * is live. Nothing is swapped at promotion — `safe-rollout` runs
 * `verify_prod_path` and ramps via `flag.control`; it never mutates this file.
 *
 * Environment-keyed model (D26): `FW_ENV_PROFILES` maps every environment the
 * project declares in FireWeave (`list_project_environments`) — the default
 * `development` plus `staging`, `production`, … — to a TIER. `dev`-tier binds the
 * in-memory FireWeave local provider + console exporters; `prod`-tier binds the
 * connected vendor's real provider + direct OTLP + the boot beacon. `staging` is a
 * FIRST-CLASS prod-tier environment — it is NEVER silently folded into dev or prod.
 * `/fireweave:initialise --reinit` regenerates this map from the environment list.
 *
 * `initFwHarness()` MUST be the FIRST awaited statement in the app entrypoint
 * (§11.6) so the provider + OTel + the stamp beacon are live before any flag
 * read or instrumented path runs. `verify_prod_path` asserts exactly that.
 *
 * Ejecting rewrites the optional `fw.flag(...)` sugar to raw
 * `await OpenFeature.getClient().getBooleanValue(...)` and strips the imports of
 * this file and fw-providers.ts. It does not delete either file — remove them
 * yourself once nothing imports them.
 */
import { OpenFeature } from '@openfeature/server-sdk';
import {
  isProd,
  initFwTelemetry,
  registerFwFlagHooks,
} from '@fireweaveai/deploy-sdk/flags';
import { initFwAttestation } from '@fireweaveai/deploy-sdk';
import { resolveBootBeaconFromEnv } from '@fireweaveai/deploy-sdk/attest';
import { makeConnectedVendorProvider, makeDevProvider } from './fw-providers';
// Plain static value import — no glob/embed/build script. `FW_STAMPS` is the
// generated const tree; it is USED (passed to initFwAttestation) so DCE can't
// drop it (the "plain-import-ships" gate).
import { FW_STAMPS } from './fw-tracker';

// Surface participation (surface-ID routing). The generated `sfc_<ULID>` claims
// THIS surface's identity; its `stamps` are THIS surface's `FW_STAMPS`.
// fw-server mints ONE `sfc_` id per surface and `/fireweave:initialise`
// RECORDS it here (Step 3f, `fw repo declare-surfaces`); never invent one and
// never reuse one across surfaces. Regenerated on `--reinit` from the same
// declaration. It is passed
// to `initFwAttestation` as `surfaces` so new fw-servers attribute deploy
// liveness PER SURFACE, while `stamps: FW_STAMPS` stays the deduped union for
// older servers (dual-emit — the SDK folds surface stamps into that union).
const FW_SURFACES = [{ surfaceId: 'sfc_REPLACE_ON_INIT', stamps: FW_STAMPS }];

type FwEnvTier = 'dev' | 'prod';

/**
 * Per-environment harness profile — the environment-keyed selector (D26).
 * `/fireweave:initialise` REGENERATES this map from `list_project_environments`
 * so it mirrors the environments configured in FireWeave. Add a row here (or run
 * `--reinit`) when you add an environment so the harness classifies it EXPLICITLY
 * instead of guessing. `FW_DEFAULT_ENV` is the project's `defaultEnvironment` —
 * the row used when nothing is set at runtime.
 */
const FW_DEFAULT_ENV = 'development';
const FW_ENV_PROFILES: Record<string, { tier: FwEnvTier }> = {
  development: { tier: 'dev' },
  staging: { tier: 'prod' },
  production: { tier: 'prod' },
};

// ── Environment source — GENERATED by `/fireweave:initialise` ────────────────
// FireWeave reads THIS project's OWN environment signal — you do NOT need to
// introduce a FireWeave-specific `FW_ENV`. `/fireweave:initialise` asks how this
// repo/CI determines its live environment and generates `readEnvSignal` below to
// read YOUR var (`NODE_ENV`, a platform var like `RAILWAY_ENVIRONMENT` /
// `RENDER` / `FLY_APP_NAME`, or a repo function). `FW_ENV` is retained ONLY as an
// optional last-resort override. Regenerated on `--reinit` — edit via the skill.
// fw:env-source
function readEnvSignal(env: Record<string, string | undefined>): string | undefined {
  // Default before init tailors it to your platform: NODE_ENV, then the optional
  // FW_ENV override. `/fireweave:initialise` replaces the first read per your answer.
  return env.NODE_ENV ?? env.FW_ENV;
}
// Map a raw signal value → a FireWeave environment NAME (a key of FW_ENV_PROFILES).
// initialise fills this only when your values differ from the FireWeave names
// (e.g. { production: 'prod', preview: 'uat' }). Empty = identity mapping.
const FW_ENV_ALIASES: Record<string, string> = {};
// ─────────────────────────────────────────────────────────────────────────────

/** Resolve the running environment NAME from the project's own signal (above). */
function resolveFwEnvName(env: Record<string, string | undefined>): string {
  const raw = (readEnvSignal(env) ?? FW_DEFAULT_ENV).trim();
  return FW_ENV_ALIASES[raw] ?? raw;
}

export async function initFwHarness(): Promise<void> {
  const fwEnvName = resolveFwEnvName(process.env);
  const profile = FW_ENV_PROFILES[fwEnvName];
  // Unknown environment is NOT silently folded into dev/prod — fall back to the
  // isProd() tier probe and WARN so the operator adds an explicit profile row.
  const prod = profile ? profile.tier === 'prod' : isProd(process.env);
  if (!profile) {
    console.warn(
      `[fireweave] environment '${fwEnvName}' has no FW_ENV_PROFILES entry; ` +
        `classified as '${prod ? 'prod' : 'dev'}' via isProd() fallback. ` +
        `Run /fireweave:initialise --reinit or add it to FW_ENV_PROFILES.`
    );
  }

  // 1. Telemetry: dev-tier → console exporters; prod-tier → per-signal OTLP DIRECT
  //    to the vendor (traces + logs to PostHog; metrics to a metrics-capable dest).
  initFwTelemetry(prod ? 'rollout' : 'dev', {
    serviceName: 'fireweave-app',
    // In prod, initialise fills `signals` when an observability vendor is BOUND.
    // The bound capability names the VENDOR only — it is FireWeave's query leg
    // (how fw-server reads guardrail metrics back). The export leg is yours:
    // endpoint + credential come from env vars you set in the deploy target,
    // exactly like FW_ATTEST_URL / FW_PROJECT_API_KEY. There is no
    // `otlpEndpoint` in any capability descriptor — do not wait for one (FIR-354).
    //
    // Shape (OpenObserve; take each vendor's contract from its own docs):
    //   signals: {
    //     traces:  { endpoint: `${OO_URL}/v1/traces`,  headers: { Authorization: OO_AUTH } },
    //     logs:    { endpoint: `${OO_URL}/v1/logs`,    headers: { Authorization: OO_AUTH } },
    //     metrics: { endpoint: `${OO_URL}/v1/metrics`, headers: { Authorization: OO_AUTH } },
    //   }
    // where OO_URL = `https://<host>/api/<org>` (NO trailing slash) and
    // OO_AUTH = `Basic ${base64(email:password)}`.
  });
  registerFwFlagHooks();

  // 2. Flags: prod-tier → connected vendor provider (reads THIS environment's
  //    credentials from process.env); dev-tier → FireWeave local provider.
  const provider = prod ? makeConnectedVendorProvider() : makeDevProvider();
  await OpenFeature.setProviderAndWait(provider);

  // 3. Boot beacon: attest active change stamps to the customer's own fw-server.
  //    The beacon is labelled with the harness-resolved environment NAME
  //    (`fwEnvName`) — from THIS project's own env signal, no FireWeave-specific
  //    FW_ENV required. Requires FW_ATTEST_URL + FW_PROJECT_API_KEY in the
  //    prod-tier runtime env.
  initFwAttestation({
    stamps: FW_STAMPS,
    surfaces: FW_SURFACES,
    ...resolveBootBeaconFromEnv({ env: process.env, prod, environment: fwEnvName }),
  });
}
