/**
 * fw-providers.ts — scaffolded by `/fireweave:initialise` (TS-server surface).
 *
 * `makeConnectedVendorProvider()` is the prod control-point client with a
 * CONCRETE body: it reads `FW_PROJECT_API_KEY` + `FW_API_URL` (falls back to
 * the legacy-named `FW_ATTEST_URL`, which older provisioning wrote — same
 * fw-server base URL) and hands them to `initFireweave()` from
 * `@fireweaveai/server-sdk`, which brings up the remote adapter against
 * fw-server `POST /v1/flags/evaluate`.
 *
 * **The SDK reads no environment variables at all** (spec/modes.md) — this
 * file is the seam where those two vars become explicit options. That is
 * deliberate: env reading belongs to the harness you own, which is what keeps
 * the SDK bundler-safe and deterministic under test. Apps do NOT embed vendor
 * keys — which backend fw-server forwards to is fw-server's concern.
 *
 * `mode` is REQUIRED and never inferred (spec/modes.md). A missing credential
 * is a boot error here, never a silent fall-back to local evaluation — that
 * failure mode looks like a green boot and a feature that never ramps, which
 * is indistinguishable from a rollout nobody started.
 *
 * `registerFwTarget()` is the OTHER half of targeting. Rules match on two kinds
 * of property and you need both:
 *   - DURABLE — registered here, once per login / device provisioning: plan,
 *     beta membership, region, device model. Stored server-side, so rules keep
 *     matching without the app resending anything, and backend systems can set
 *     facts the client never knows.
 *   - PER-REQUEST — the per-call evaluation context: page, session, experiment
 *     context. Overrides the registered value for that one call.
 * A rule targeting a property that is never registered AND never sent matches
 * nobody, silently. Register the durable facts at sign-in.
 *
 * `getFwClient()` is how the rest of the app reaches the client
 * `initFwHarness()` brought up — `fw.controlPoints` in fw-harness.ts resolves
 * it from here rather than re-running init. Both tiers go through the SAME
 * `initFireweave()` call shape, so dev and prod cannot skew in lifecycle
 * gating, context canonicalization, or validation.
 *
 * Observability is NOT wired here. FireWeave does not take responsibility for
 * wiring an observability SDK into a repo that has not chosen one.
 */
import {
  initFireweave,
  type FireweaveClient,
  type RegisterTargetOptions,
  type RegisterTargetResult,
} from '@fireweaveai/server-sdk';

/** Set by whichever factory below `initFwHarness()` calls — dev and prod both go through it. */
let fwClient: FireweaveClient | null = null;

function resolveFwApiUrl(env: Record<string, string | undefined>): string {
  return (env.FW_API_URL ?? env.FW_ATTEST_URL ?? '').replace(/\/+$/, '');
}

/**
 * Hosts the SDK is permitted to talk to, derived from the URL you configured.
 *
 * REQUIRED for a self-hosted fw-server, not optional hardening. `initFireweave`
 * validates `apiUrl` against a CANONICAL allowlist (the fireweave.ai hosts plus
 * loopback) when `allowedHosts` is omitted, so a customer-run fw-server on any
 * other hostname fails initialisation with a bare `Configuration` error that
 * names nothing. Passing the configured host explicitly is what makes
 * self-hosting work; it is still an allowlist, so it stays an SSRF guard.
 */
function allowedHostsFor(apiUrl: string): string[] {
  try {
    return [new URL(apiUrl).hostname, 'localhost', '127.0.0.1'];
  } catch {
    return ['localhost', '127.0.0.1'];
  }
}

// ── Environment-keyed tier model (D26) — GENERATED by `/fireweave:initialise` ──
// This lives here, not in fw-harness.ts, so the file you review stays about ten
// lines. `initialise` REGENERATES this map from `list_project_environments` so
// it mirrors the environments configured in FireWeave. Add a row (or run
// `--reinit`) when you add an environment, so the harness classifies it
// EXPLICITLY instead of guessing. `staging` is a FIRST-CLASS prod-tier
// environment — it is NEVER silently folded into dev.
const FW_DEFAULT_ENV = 'prod';
const FW_ENV_PROFILES: Record<string, { tier: 'dev' | 'prod' }> = {
  prod: { tier: 'prod' },
};

// FireWeave reads THIS project's OWN environment signal — you do NOT need to
// introduce a FireWeave-specific `FW_ENV`. `/fireweave:initialise` asks how this
// repo/CI determines its live environment and generates `readEnvSignal` to read
// YOUR var (`NODE_ENV`, a platform var like `RAILWAY_ENVIRONMENT` / `RENDER` /
// `FLY_APP_NAME`, or a repo function). `FW_ENV` is retained ONLY as an optional
// last-resort override. Regenerated on `--reinit` — edit via the skill.
// fw:env-source
function readEnvSignal(
  env: Record<string, string | undefined>
): string | undefined {
  return env.APP_ENV ?? env.FW_ENV;
}

// Map a raw signal value → a FireWeave environment NAME (a key of
// FW_ENV_PROFILES). initialise fills this only when your values differ from the
// FireWeave names (e.g. { production: 'prod', preview: 'uat' }). Empty = identity.
const FW_ENV_ALIASES: Record<string, string> = {};

/** Resolve the running environment NAME from the project's own signal above. */
function resolveFwEnvName(env: Record<string, string | undefined>): string {
  const raw = (readEnvSignal(env) ?? FW_DEFAULT_ENV).trim();
  return FW_ENV_ALIASES[raw] ?? raw;
}

const PROD_FW_ENV = new Set(['prod', 'production', 'rollout']);
const NON_PROD_FW_ENV = new Set(['dev', 'development', 'test', 'local']);

/** Last-resort tier probe for an environment with no FW_ENV_PROFILES row. */
function isProdFallback(env: Record<string, string | undefined>): boolean {
  const fw = env.FW_ENV?.toLowerCase();
  if (fw) {
    if (PROD_FW_ENV.has(fw)) return true;
    if (NON_PROD_FW_ENV.has(fw)) return false;
  }
  return env.NODE_ENV?.toLowerCase() === 'production';
}

/**
 * Is this process a prod-tier environment? The tier decision `fw-harness.ts`
 * branches on. An UNKNOWN environment is never silently folded into dev or
 * prod — it falls back to the probe above and WARNS, so the operator adds an
 * explicit row rather than discovering the classification from behaviour.
 */
export function isProd(
  env: Record<string, string | undefined> = process.env
): boolean {
  const name = resolveFwEnvName(env);
  const profile = FW_ENV_PROFILES[name];
  if (profile) return profile.tier === 'prod';
  const prod = isProdFallback(env);
  console.warn(
    `[fireweave] environment '${name}' has no FW_ENV_PROFILES entry; ` +
      `classified as '${prod ? 'prod' : 'dev'}' via the fallback probe. ` +
      `Run /fireweave:initialise --reinit or add it to FW_ENV_PROFILES.`
  );
  return prod;
}

/** PROD: Fireweave remote mode → fw-server /v1/flags/evaluate. */
export async function makeConnectedVendorProvider(): Promise<FireweaveClient> {
  const apiUrl = resolveFwApiUrl(process.env);
  const apiKey = process.env.FW_PROJECT_API_KEY?.trim() ?? '';
  if (!apiUrl || !apiKey) {
    throw new Error(
      '[fireweave] prod control points require FW_PROJECT_API_KEY and FW_API_URL (or FW_ATTEST_URL)'
    );
  }
  await loadInstanceId();
  fwClient = await initFireweave({
    mode: 'remote',
    apiUrl,
    apiKey,
    allowedHosts: allowedHostsFor(apiUrl),
  });
  return fwClient;
}

/**
 * DEV: the SDK's local mode — an in-process seeded map, no network, no
 * credentials. Same `initFireweave()` entry point as prod, so the two tiers
 * share validation and lifecycle gating and the harness cannot skew.
 *
 * Call-site / manifest defaults stay `false` (RAMP-1). To dogfood a control
 * point ON locally, seed it here — never `fw.flag(key, true)` (that same `true`
 * is the prod fallback when the key is missing from the backend):
 *
 *   local: { controlPoints: { '<feature-slug>': true } },
 */
export async function makeDevProvider(): Promise<FireweaveClient> {
  await loadInstanceId();
  fwClient = await initFireweave({
    mode: 'local',
    local: { controlPoints: { "mood-chip": true } },
  });
  return fwClient;
}

/**
 * Register a user or device for DURABLE targeting. Call once from your auth
 * middleware / sign-in handler, then pass the SAME id as `targetingKey` in the
 * per-call evaluation context:
 *
 *   await registerFwTarget(user.id, {
 *     properties: { plan: user.plan, beta: user.inBeta },
 *   });
 *
 * Resolves rather than throwing — it runs in sign-in paths, where a targeting
 * concern must not break authentication. Both tiers route through the SAME
 * client: prod sends it to fw-server; local records it in-process and traces one
 * `[fireweave:local]` line saying nothing was sent (spec/modes.md). Neither
 * silently pretends to have registered anything. Log `ok: false` — a silently
 * unregistered target is exactly how targeting rules end up matching nobody.
 */
export async function registerFwTarget(
  targetingKey: string,
  options: RegisterTargetOptions = {}
): Promise<RegisterTargetResult> {
  if (!fwClient) return { ok: false };
  return fwClient.registerTarget(targetingKey, options);
}

/**
 * PERSISTED instance identity — a stable targeting key for reads with no user
 * in scope.
 *
 * **This is not a substitute for the user id.** Every request-path read must
 * pass the real subject: `fw.flag(key, false, { targetingKey: user.id })`. A
 * server serves many users, so bucketing them all on one instance id is exactly
 * the single-bucket bug this file otherwise avoids.
 *
 * What it IS for: reads where the SERVER is genuinely the subject — a cron job,
 * a migration, a background worker, a boot-time decision. Those have no user,
 * and without a stable key they either fail `InvalidContext` or re-bucket on
 * every process restart, so a 10% ramp reshuffles which instances are on at
 * each deploy.
 *
 * Persisted next to the harness so it survives restarts; falls back to a
 * process-lifetime id when the filesystem is read-only (a container with no
 * writable volume), which is still stable for the life of that process.
 */
const FW_INSTANCE_ID_FILE = '.fireweave/instance-id';
let fwInstanceId: string | null = null;

function mintInstanceId(): string {
  const rand =
    globalThis.crypto?.randomUUID?.() ??
    `${Math.random().toString(36).slice(2)}${Date.now().toString(36)}`;
  return `inst_${rand}`;
}

/**
 * Load (or mint) the persisted instance id. Called once during harness boot,
 * which is why it can be async — and it HAS to be.
 *
 * A synchronous `require('node:fs')` was the obvious implementation and it is
 * quietly wrong: under ESM on Bun and Node there is no `globalThis.require`, so
 * every call fell to the catch and returned a fresh process-lifetime id. The
 * harness still "worked" and the id was still stable within the process, so
 * nothing failed — it just silently stopped being PERSISTED on FireWeave's own
 * default runtime, which is the entire property this function exists for. A
 * dynamic import resolves on Node, Bun and Deno alike.
 */
async function loadInstanceId(): Promise<string> {
  if (fwInstanceId !== null) return fwInstanceId;
  // Interface + non-literal specifier so this compiles in a repo with NO
  // `@types/node` installed. A literal `import('node:fs/promises')` makes tsc
  // demand those types, which is an install the customer never asked for just
  // to typecheck a file FireWeave scaffolded.
  interface MinimalFsPromises {
    readFile(p: string, enc: 'utf8'): Promise<string>;
    mkdir(p: string, o: { recursive: boolean }): Promise<unknown>;
    writeFile(p: string, data: string): Promise<void>;
  }
  try {
    const specifier = 'node:fs/promises';
    const fs = (await import(specifier)) as unknown as MinimalFsPromises;
    try {
      const existing = (await fs.readFile(FW_INSTANCE_ID_FILE, 'utf8')).trim();
      if (existing) return (fwInstanceId = existing);
    } catch {
      // Not yet written — fall through and mint.
    }
    const minted = mintInstanceId();
    await fs.mkdir('.fireweave', { recursive: true });
    await fs.writeFile(FW_INSTANCE_ID_FILE, `${minted}\n`);
    return (fwInstanceId = minted);
  } catch {
    // Read-only filesystem (a container with no writable volume) or no fs at
    // all. A process-lifetime id is still stable for the life of the process,
    // which is the honest degradation — it re-buckets on restart, and this
    // comment is the only warning anyone will get about that.
    return (fwInstanceId = mintInstanceId());
  }
}

/**
 * A stable targeting key for reads with NO user in scope.
 *
 * **Not a substitute for the user id.** Every request-path read must pass the
 * real subject: `fw.flag(key, false, { targetingKey: user.id })`. A server
 * serves many users, so bucketing them all on one instance id is exactly the
 * single-bucket bug this harness otherwise avoids.
 *
 * What it IS for: reads where the SERVER is genuinely the subject — a cron job,
 * a migration, a background worker, a boot-time decision. Those have no user,
 * and without a stable key they either fail `InvalidContext` or re-bucket on
 * every restart, so a 10% ramp reshuffles which instances are on at each deploy.
 */
export function resolveInstanceTargetingKey(): string {
  // Non-null after `initFwHarness()`; the mint here only covers a call made
  // before boot, and it is cached so the value never changes mid-process.
  return (fwInstanceId ??= mintInstanceId());
}

/** The client `initFwHarness()` brought up — call-sites read control points through this. */
export function getFwClient(): FireweaveClient {
  if (!fwClient) {
    throw new Error(
      '[fireweave] getFwClient() called before initFwHarness() finished — await it first.'
    );
  }
  return fwClient;
}
