//! fw_providers.rs — scaffolded by `/fireweave:initialise` (RUST surface).
//!
//! `make_connected_vendor_provider()` is the prod control-point client with a
//! CONCRETE body: it reads `FW_PROJECT_API_KEY` + `FW_API_URL` (falling back to
//! the legacy-named `FW_ATTEST_URL`, which older provisioning wrote — same
//! fw-server base URL) and hands them to `init_fireweave()`, which brings up the
//! remote adapter against fw-server `POST /v1/flags/evaluate`.
//!
//! **The SDK reads no environment variables at all** (spec/modes.md) — this file
//! is the seam where those two vars become explicit options. That is deliberate:
//! env reading belongs to the harness you own, which keeps the SDK deterministic
//! under test. Apps do NOT embed vendor keys — which backend fw-server forwards
//! to is fw-server's concern.
//!
//! `mode` is REQUIRED and never inferred (spec/modes.md). A missing credential
//! is a boot error here, never a silent fall-back to local evaluation — that
//! failure mode looks like a green boot and a feature that never ramps, which is
//! indistinguishable from a rollout nobody started.
//!
//! `register_fw_target()` is the OTHER half of targeting. Rules match on two
//! kinds of property and you need both: DURABLE facts registered once at sign-in
//! (plan, beta membership, region), and PER-REQUEST context passed to each
//! evaluation. A rule targeting a property that is never registered AND never
//! sent matches nobody, silently.

use std::collections::HashMap;
use std::env;
use std::sync::OnceLock;

use fireweave::{
    init_fireweave, FireweaveClient, FireweaveError, InitOptions, RegisterTargetOptions,
};

// ── Environment-keyed tier model (D26) — GENERATED by `/fireweave:initialise` ──
// This lives here, not in fw_harness.rs, so the file you review stays small.
// `initialise` REGENERATES this map from `list_project_environments`. Add a row
// (or run `--reinit`) when you add an environment so the harness classifies it
// EXPLICITLY. "staging" is a FIRST-CLASS prod-tier environment — it is NEVER
// silently folded into dev.
const FW_DEFAULT_ENV: &str = "development";

fn fw_env_profiles() -> HashMap<&'static str, &'static str> {
    HashMap::from([
        ("development", "dev"),
        ("staging", "prod"),
        ("production", "prod"),
    ])
}

/// FireWeave reads THIS project's OWN environment signal — you do NOT need to
/// introduce a FireWeave-specific `FW_ENV`. `/fireweave:initialise` asks how this
/// repo/CI determines its live environment and generates `read_env_signal` below
/// to read YOUR var (`APP_ENV` / `ENVIRONMENT` / a platform var). `FW_ENV` is
/// retained ONLY as an optional last-resort override. Regenerated on `--reinit`.
// fw:env-source
fn read_env_signal() -> Option<String> {
    for key in ["APP_ENV", "ENVIRONMENT", "ENV", "FW_ENV"] {
        if let Ok(v) = env::var(key) {
            let v = v.trim().to_string();
            if !v.is_empty() {
                return Some(v);
            }
        }
    }
    None
}

/// Map a raw signal value -> a FireWeave environment NAME (a key of
/// `fw_env_profiles`). initialise fills this only when your values differ from
/// the FireWeave names (e.g. `[("prod", "production")]`). Empty = identity.
fn fw_env_aliases() -> HashMap<&'static str, &'static str> {
    HashMap::new()
}

/// Resolve the running environment NAME from the project's own signal above.
pub fn resolve_fw_env_name() -> String {
    let raw = read_env_signal().unwrap_or_else(|| FW_DEFAULT_ENV.to_string());
    fw_env_aliases()
        .get(raw.as_str())
        .map(|s| (*s).to_string())
        .unwrap_or(raw)
}

/// Is this process a prod-tier environment? The tier decision `fw_harness.rs`
/// branches on, and the token `verify_prod_path` greps for.
///
/// An UNKNOWN environment is never silently folded into dev or prod: it warns,
/// so the operator adds an explicit row rather than discovering the
/// classification from behaviour.
pub fn is_prod() -> bool {
    let name = resolve_fw_env_name();
    match fw_env_profiles().get(name.as_str()) {
        Some(tier) => *tier == "prod",
        None => {
            eprintln!(
                "[fireweave] environment '{name}' has no fw_env_profiles entry; \
                 classified as 'dev'. Run /fireweave:initialise --reinit or add \
                 it to fw_env_profiles."
            );
            false
        }
    }
}

static FW_CLIENT: OnceLock<FireweaveClient> = OnceLock::new();

/// Fires at most once. A silent fallback never clears itself: the deploy
/// environment keeps the old variable forever because nothing tells anyone it
/// is old. A warning, not an error — a rename must not take a service down.
static WARNED_LEGACY_API_URL: OnceLock<()> = OnceLock::new();

fn resolve_fw_api_url() -> String {
    if let Ok(raw) = env::var("FW_API_URL") {
        if !raw.is_empty() {
            return raw.trim_end_matches('/').to_string();
        }
    }
    if let Ok(legacy) = env::var("FW_ATTEST_URL") {
        if !legacy.is_empty() {
            WARNED_LEGACY_API_URL.get_or_init(|| {
                eprintln!(
                    "[fireweave] FW_ATTEST_URL is a legacy name for the fw-server base \
                     URL. Rename it to FW_API_URL in this environment — the value does \
                     not change. See fireweave.md."
                );
            });
            return legacy.trim_end_matches('/').to_string();
        }
    }
    String::new()
}

/// Keeps a SELF-HOSTED fw-server reachable. Omit `allowed_hosts` and the SDK
/// validates `api_url` against a canonical `*.fireweave.ai` + loopback
/// allowlist, so a customer-run fw-server on any other hostname fails init with
/// a bare `Configuration` error naming nothing.
fn allowed_hosts_for(api_url: &str) -> Vec<String> {
    let host = api_url
        .split("://")
        .nth(1)
        .and_then(|rest| rest.split('/').next())
        .map(|hostport| hostport.split(':').next().unwrap_or("").to_string())
        .filter(|h| !h.is_empty());
    match host {
        Some(h) => vec![h, "localhost".to_string(), "127.0.0.1".to_string()],
        None => vec!["localhost".to_string(), "127.0.0.1".to_string()],
    }
}

/// PROD: Fireweave remote mode -> fw-server `/v1/flags/evaluate`.
pub fn make_connected_vendor_provider() -> Result<(), FireweaveError> {
    let api_url = resolve_fw_api_url();
    let api_key = env::var("FW_PROJECT_API_KEY").unwrap_or_default();
    let options = InitOptions::remote(api_key, api_url.clone())
        .with_allowed_hosts(allowed_hosts_for(&api_url));
    let client = init_fireweave(options)?;
    let _ = FW_CLIENT.set(client);
    Ok(())
}

/// DEV: Fireweave local mode — no credentials, no network. Seed a key here to
/// dogfood a feature ON locally; never by passing `true` as a call-site default.
pub fn make_dev_provider() -> Result<(), FireweaveError> {
    let control_points: HashMap<String, bool> = HashMap::new();
    let client = init_fireweave(InitOptions::local_with_control_points(control_points))?;
    let _ = FW_CLIENT.set(client);
    Ok(())
}

/// Store DURABLE targeting facts server-side, so rules keep matching without
/// the app resending them on every request.
///
/// `register_target` RESOLVES `ok: false` rather than failing — it runs in
/// sign-in paths, where a targeting concern must not break authentication.
/// Surfacing it as a `Result` here is what makes the failure loggable instead of
/// discarded: a silently unregistered target is how a rule matches nobody.
pub fn register_fw_target(
    targeting_key: &str,
    options: Option<&RegisterTargetOptions>,
) -> Result<(), FireweaveError> {
    let res = get_fw_client().register_target(targeting_key, options);
    if res.ok {
        return Ok(());
    }
    Err(res
        .error
        .unwrap_or_else(|| FireweaveError::new(fireweave::ErrorKind::Internal)))
}

/// The client `init_fw_harness()` brought up — call sites read control points
/// through this rather than re-running init, so dev and prod cannot diverge at
/// the read path.
///
/// Panics only on genuine programmer error: a read before `init_fw_harness()`.
/// That is a boot-order bug, not a runtime condition to degrade through — the
/// alternative is serving every default with a green log.
pub fn get_fw_client() -> &'static FireweaveClient {
    FW_CLIENT
        .get()
        .expect("fireweave: read before init_fw_harness() — call it first in main()")
}
