/**
 * fw-harness.ts — scaffolded by `/fireweave:initialise` (WEB / browser surface).
 *
 * The web peer of the server harness: same "promote, not wrap" shape and the same
 * environment-keyed `FW_ENV_PROFILES` selector, but the web SDK is SYNCHRONOUS —
 * flag READS at the call-sites carry NO `await` (the web invariant the eject
 * codemod depends on). The harness BOOT is still async (it awaits provider
 * readiness once at start). On the web the running environment is resolved from
 * the app's OWN build-baked `import.meta.env` signal (Vite `MODE` by default;
 * `/fireweave:initialise` tailors `readEnvSignal` below), so `staging` builds bind
 * the connected vendor as a first-class prod-tier surface — no `PUBLIC_FW_ENV` var
 * required (it stays an optional override only).
 *
 * `initFwHarness()` MUST be awaited first in the app's bootstrap, before the
 * first render that reads a flag. Ejecting rewrites `fw.flag(...)` to raw sync
 * `OpenFeature.getClient().getBooleanValue(...)` and strips the imports of this
 * file and fw-providers.ts; it does not delete either — remove them yourself
 * once nothing imports them.
 */
import { OpenFeature } from '@openfeature/web-sdk';
import {
  isProd,
  initFwTelemetry,
  registerFwWebFlagHooks,
} from '@fireweaveai/deploy-sdk/flags/web';
import { makeConnectedVendorProvider, makeDevProvider } from './fw-providers';
// The `fw-tracker/` const tree stays on disk as the committed stamp record —
// `reconcile` and the dev-checklist gates read it from the repo, so it needs
// no import here.

type FwEnvTier = 'dev' | 'prod';

/**
 * Per-environment harness profile — the environment-keyed selector (D26).
 * `/fireweave:initialise` REGENERATES this map from `list_project_environments`.
 * Add a row (or run `--reinit`) when you add an environment so the harness
 * classifies it EXPLICITLY. `FW_DEFAULT_ENV` is the `defaultEnvironment`.
 */
const FW_DEFAULT_ENV = 'prod';
const FW_ENV_PROFILES: Record<string, { tier: FwEnvTier }> = {
  prod: { tier: 'prod' },
};

// ── Environment source — GENERATED by `/fireweave:initialise` ────────────────
// FireWeave reads THIS app's OWN build-baked env signal — you do NOT need to add
// a FireWeave-specific `PUBLIC_FW_ENV` / `VITE_FW_ENV`. `/fireweave:initialise`
// asks how this app determines its environment and generates `readEnvSignal`
// below to read YOUR signal (Vite `MODE`, a `PUBLIC_*` / `VITE_*` app var, etc.).
// `PUBLIC_FW_ENV` / `VITE_FW_ENV` are retained ONLY as an optional override.
// Regenerated on `--reinit` — edit via the skill.
// fw:env-source
function readEnvSignal(env: Record<string, string | undefined> | undefined): string | undefined {
  // App env signal (Step 3d): VITE_APP_ENV from compose / Vite. FireWeave vars are optional override.
  return env?.VITE_APP_ENV ?? env?.PUBLIC_FW_ENV ?? env?.VITE_FW_ENV;
}
// Map a raw signal value → a FireWeave environment NAME (a key of FW_ENV_PROFILES).
// Vite MODE is often 'production'/'development'; alias to your FireWeave names
// (e.g. { production: 'prod' }) when they differ. Empty = identity mapping.
const FW_ENV_ALIASES: Record<string, string> = {};
// ─────────────────────────────────────────────────────────────────────────────

/** Resolve the running environment NAME from the app's own build-baked signal (above). */
function resolveFwEnvName(env: Record<string, string | undefined> | undefined): string {
  const raw = (readEnvSignal(env) ?? FW_DEFAULT_ENV).trim();
  return FW_ENV_ALIASES[raw] ?? raw;
}

export async function initFwHarness(): Promise<void> {
  const viteEnv = import.meta.env as Record<string, string | undefined> | undefined;
  const fwEnvName = resolveFwEnvName(viteEnv);
  const profile = FW_ENV_PROFILES[fwEnvName];
  // Unknown environment is NOT silently folded — fall back to the isProd() tier
  // probe and WARN so the operator adds an explicit profile row.
  const prod = profile ? profile.tier === 'prod' : isProd(viteEnv);
  if (!profile) {
    console.warn(
      `[fireweave] environment '${fwEnvName}' has no FW_ENV_PROFILES entry; ` +
        `classified as '${prod ? 'prod' : 'dev'}' via isProd() fallback. ` +
        `Run /fireweave:initialise --reinit or add it to FW_ENV_PROFILES.`
    );
  }

  // Telemetry: dev-tier → console; prod-tier → per-signal OTLP DIRECT to the
  // vendor (OTLP-over-fetch works in the browser). The boot is async; reads sync.
  initFwTelemetry(prod ? 'rollout' : 'dev', { serviceName: 'fireweave-web-app' });
  registerFwWebFlagHooks();

  const provider = prod ? makeConnectedVendorProvider() : makeDevProvider();
  // Awaits the provider's FIRST flag set so the synchronous reads that follow
  // resolve against real values — the per-call reads themselves are sync.
  await OpenFeature.setProviderAndWait(provider);
}
