// Package fireweave — fw_providers.go, scaffolded by `/fireweave:initialise`
// (GO surface).
//
// MakeConnectedVendorProvider() is the prod control-point client with a
// CONCRETE body: it reads FW_PROJECT_API_KEY + FW_API_URL (falling back to the
// legacy-named FW_ATTEST_URL, which older provisioning wrote — same fw-server
// base URL) and hands them to fireweave.Init(), which brings up the remote
// adapter against fw-server POST /v1/flags/evaluate.
//
// **The SDK reads no environment variables at all** (spec/modes.md) — this file
// is the seam where those two vars become explicit options. That is deliberate:
// env reading belongs to the harness you own, which keeps the SDK deterministic
// under test. Apps do NOT embed vendor keys — which backend fw-server forwards
// to is fw-server's concern.
//
// Mode is REQUIRED and never inferred (spec/modes.md). A missing credential is
// a boot error here, never a silent fall-back to local evaluation — that
// failure mode looks like a green boot and a feature that never ramps, which is
// indistinguishable from a rollout nobody started.
//
// RegisterFwTarget() is the OTHER half of targeting. Rules match on two kinds of
// property and you need both: DURABLE facts registered once at sign-in (plan,
// beta membership, region), and PER-REQUEST context passed to each evaluation.
// A rule targeting a property that is never registered AND never sent matches
// nobody, silently.
package fireweave

import (
	"fmt"
	"net/url"
	"os"
	"strings"
	"sync"

	"github.com/FireWeave-HQ/fireweave-sdk/sdks/go/fireweave"
)

// ── Environment-keyed tier model (D26) — GENERATED by `/fireweave:initialise` ──
// This lives here, not in fw_harness.go, so the file you review stays small.
// `initialise` REGENERATES this map from `list_project_environments`. Add a row
// (or run `--reinit`) when you add an environment so the harness classifies it
// EXPLICITLY. "staging" is a FIRST-CLASS prod-tier environment — it is NEVER
// silently folded into dev.
const fwDefaultEnv = "development"

var fwEnvProfiles = map[string]string{
	"development": "dev",
	"staging":     "prod",
	"production":  "prod",
}

// FireWeave reads THIS project's OWN environment signal — you do NOT need to
// introduce a FireWeave-specific FW_ENV. `/fireweave:initialise` asks how this
// repo/CI determines its live environment and generates readEnvSignal below to
// read YOUR var (APP_ENV / ENVIRONMENT / a platform var). FW_ENV is retained
// ONLY as an optional last-resort override. Regenerated on `--reinit`.
// fw:env-source
func readEnvSignal() string {
	for _, k := range []string{"APP_ENV", "ENVIRONMENT", "ENV", "FW_ENV"} {
		if v := strings.TrimSpace(os.Getenv(k)); v != "" {
			return v
		}
	}
	return ""
}

// Map a raw signal value -> a FireWeave environment NAME (a key of
// fwEnvProfiles). initialise fills this only when your values differ from the
// FireWeave names (e.g. {"prod": "production"}). Empty = identity mapping.
var fwEnvAliases = map[string]string{}

// ResolveFwEnvName resolves the running environment NAME from the project's own
// signal above.
func ResolveFwEnvName() string {
	raw := readEnvSignal()
	if raw == "" {
		raw = fwDefaultEnv
	}
	if mapped, ok := fwEnvAliases[raw]; ok {
		return mapped
	}
	return raw
}

// IsProd reports whether this process is a prod-tier environment — the tier
// decision fw_harness.go branches on, and the token `verify_prod_path` greps
// for.
//
// An UNKNOWN environment is never silently folded into dev or prod: it warns,
// so the operator adds an explicit row rather than discovering the
// classification from behaviour.
func IsProd() bool {
	name := ResolveFwEnvName()
	tier, ok := fwEnvProfiles[name]
	if ok {
		return tier == "prod"
	}
	fmt.Fprintf(os.Stderr,
		"[fireweave] environment %q has no fwEnvProfiles entry; classified as "+
			"'dev'. Run /fireweave:initialise --reinit or add it to fwEnvProfiles.\n",
		name)
	return false
}

var (
	fwClientMu sync.RWMutex
	fwClient   *fireweave.Client
)

func resolveFwAPIURL() string {
	raw := os.Getenv("FW_API_URL")
	if raw == "" {
		raw = os.Getenv("FW_ATTEST_URL")
	}
	return strings.TrimRight(raw, "/")
}

// allowedHostsFor keeps a SELF-HOSTED fw-server reachable. Omit AllowedHosts and
// the SDK validates APIURL against a canonical *.fireweave.ai + loopback
// allowlist, so a customer-run fw-server on any other hostname fails init with a
// bare Configuration error naming nothing.
func allowedHostsFor(apiURL string) []string {
	parsed, err := url.Parse(apiURL)
	if err != nil || parsed.Hostname() == "" {
		return []string{"localhost", "127.0.0.1"}
	}
	return []string{parsed.Hostname(), "localhost", "127.0.0.1"}
}

// MakeConnectedVendorProvider is PROD: Fireweave remote mode -> fw-server
// /v1/flags/evaluate.
func MakeConnectedVendorProvider() error {
	apiURL := resolveFwAPIURL()
	client, err := fireweave.Init(fireweave.Options{
		Mode:         fireweave.ModeRemote,
		APIKey:       os.Getenv("FW_PROJECT_API_KEY"),
		APIURL:       apiURL,
		AllowedHosts: allowedHostsFor(apiURL),
	})
	if err != nil {
		return fmt.Errorf("fireweave: prod init failed: %w", err)
	}
	fwClientMu.Lock()
	fwClient = client
	fwClientMu.Unlock()
	return nil
}

// MakeDevProvider is DEV: Fireweave local mode — no credentials, no network.
// Seed a key in ControlPoints to dogfood a feature ON locally; never by passing
// true as a call-site default.
func MakeDevProvider() error {
	client, err := fireweave.Init(fireweave.Options{
		Mode: fireweave.ModeLocal,
		Local: &fireweave.LocalOptions{
			ControlPoints: map[string]bool{},
		},
	})
	if err != nil {
		return fmt.Errorf("fireweave: dev init failed: %w", err)
	}
	fwClientMu.Lock()
	fwClient = client
	fwClientMu.Unlock()
	return nil
}

// RegisterFwTarget stores DURABLE targeting facts server-side, so rules keep
// matching without the app resending them on every request. Resolves rather
// than failing the caller — this runs in sign-in paths, where a targeting
// concern must not break authentication. LOG a non-nil error: a silently
// unregistered target is exactly how a rule ends up matching nobody.
func RegisterFwTarget(targetKey string, opts *fireweave.RegisterTargetOptions) error {
	client := GetFwClient()
	if client == nil {
		return fmt.Errorf("fireweave: RegisterFwTarget before InitFwHarness")
	}
	// RegisterTarget returns a RESULT, not an error — it never fails the caller.
	// Surfacing it as an error here is what makes `ok: false` loggable instead
	// of discarded; a silently unregistered target is how a rule matches nobody.
	res := client.RegisterTarget(targetKey, opts)
	if !res.OK {
		if res.Error != nil {
			return fmt.Errorf("fireweave: registerTarget failed: %w", res.Error)
		}
		return fmt.Errorf("fireweave: registerTarget failed for %q", targetKey)
	}
	return nil
}

// GetFwClient returns the client InitFwHarness() brought up — call sites read
// control points through this rather than re-running init, so dev and prod
// cannot diverge at the read path.
func GetFwClient() *fireweave.Client {
	fwClientMu.RLock()
	defer fwClientMu.RUnlock()
	return fwClient
}
