package fireweave; // REPLACED at init: `<app base package>.fireweave` — the file
// lives in the matching source directory (Java requires dir == package).

/*
 * FwHarness.java — scaffolded by `/fireweave:initialise` (JAVA surface).
 *
 * The "promote, not wrap" harness (D26): BOTH branches are present and the
 * RUNNING ENVIRONMENT — resolved by NAME, not a bare boolean — selects which
 * one is live, via FW_ENV_PROFILES.
 *   dev  -> FireWeave local provider (in-process, no credentials)
 *   prod -> FireWeave remote provider (fw-server POST /v1/flags/evaluate)
 *
 * Nothing is swapped at promotion — `safe-rollout` ramps via `flag.control`
 * and never mutates this file.
 *
 * `initFwHarness()` MUST be the FIRST statement in `main()` (or the framework
 * bootstrap — before the Spring context refresh for a Spring Boot app) so the
 * provider is live before any flag read. It is SYNCHRONOUS. `isProd()` is
 * retained as the unknown-environment tier fallback and the token
 * `verify_prod_path` greps for.
 *
 * TELEMETRY: the `ai.fireweave` SDK carries no OpenTelemetry dependency. Wire
 * `io.opentelemetry` yourself if this app exports spans — never a half-wired
 * exporter (empty endpoint / placeholder creds), which looks configured and
 * silently drops every span.
 *
 * Ejecting rewrites the `fwFlag(...)` sugar to raw OpenFeature calls and strips
 * the imports of this file and FwProviders.java. It does not delete either file
 * — remove them yourself once nothing imports them.
 */

import dev.openfeature.sdk.MutableContext;
import dev.openfeature.sdk.OpenFeatureAPI;

import java.util.LinkedHashMap;
import java.util.Map;

public final class FwHarness {

    /**
     * env name -> tier profile — regenerated from FireWeave
     * `list_project_environments`. Keep in sync with `.fireweave/project.json`
     * `rolloutReady.environments`. FW_DEFAULT_ENV is the project's
     * `defaultEnvironment` — the row used when nothing is set at runtime.
     * `/fireweave:initialise --reinit` regenerates this map.
     */
    public static final String FW_DEFAULT_ENV = "development";

    private static final Map<String, String> FW_ENV_PROFILES = new LinkedHashMap<>();

    static {
        FW_ENV_PROFILES.put("development", "dev");
        FW_ENV_PROFILES.put("staging", "prod");
        FW_ENV_PROFILES.put("production", "prod");
    }

    // ── Environment source — GENERATED by `/fireweave:initialise` ────────────
    // FireWeave reads THIS project's OWN environment signal — you do NOT need a
    // FireWeave-specific FW_ENV. `/fireweave:initialise` asks how this repo/CI
    // determines its live environment and generates `readEnvSignal` below to
    // read YOUR var (`APP_ENV` / `SPRING_PROFILES_ACTIVE` / a platform var).
    // FW_ENV is retained ONLY as an optional last-resort override. Regenerated
    // on `--reinit` — edit via the skill.
    // fw:env-source
    private static String readEnvSignal() {
        // Default before init tailors it to your platform: common env vars,
        // then the optional FW_ENV override. `/fireweave:initialise` replaces
        // the first read per your answer.
        String v = System.getenv("APP_ENV");
        if (v == null) v = System.getenv("ENVIRONMENT");
        if (v == null) v = System.getenv("ENV");
        if (v == null) v = System.getenv("FW_ENV");
        return v;
    }

    /**
     * Raw signal value -> FireWeave environment NAME (a key of
     * FW_ENV_PROFILES). initialise fills this only when your values differ
     * from the FireWeave names (e.g. {"prod": "production"}). Empty = identity.
     */
    private static final Map<String, String> FW_ENV_ALIASES = new LinkedHashMap<>();
    // ─────────────────────────────────────────────────────────────────────────

    /** Resolve the running environment NAME from the project's own signal. */
    public static String resolveFwEnvName() {
        String raw = readEnvSignal();
        raw = (raw == null || raw.trim().isEmpty()) ? FW_DEFAULT_ENV : raw.trim();
        return FW_ENV_ALIASES.getOrDefault(raw, raw);
    }

    /** Retained tier probe + the token `verify_prod_path` greps for. */
    public static boolean isProd() {
        return "prod".equals(FW_ENV_PROFILES.get(resolveFwEnvName()));
    }

    private static volatile boolean ready;

    /** Idempotent boot — call FIRST in the app entrypoint, before any flag read. */
    public static synchronized void initFwHarness() {
        if (ready) {
            return;
        }
        ready = true;

        String fwEnvName = resolveFwEnvName();
        String profile = FW_ENV_PROFILES.get(fwEnvName);
        // Unknown environment is NOT silently folded into dev/prod — fall back
        // to the isProd() tier probe and WARN so the operator adds a profile row.
        boolean prod = profile != null ? "prod".equals(profile) : isProd();
        if (profile == null) {
            System.err.println("[fireweave] environment '" + fwEnvName
                    + "' has no FW_ENV_PROFILES entry; classified as '"
                    + (prod ? "prod" : "dev") + "' via isProd() fallback. "
                    + "Run /fireweave:initialise --reinit or add it to FW_ENV_PROFILES.");
        }

        // Flags: prod-tier -> connected vendor provider (reads THIS
        // environment's credentials from the process env); dev-tier ->
        // FireWeave local provider. Both come from the same SDK and the same
        // runtime port, so the tiers cannot skew.
        OpenFeatureAPI.getInstance().setProviderAndWait(
                prod ? FwProviders.makeConnectedVendorProvider()
                     : FwProviders.makeDevProvider());

        Runtime.getRuntime().addShutdownHook(
                new Thread(OpenFeatureAPI.getInstance()::shutdown));
    }

    /**
     * Flag-eval facade. Call after `initFwHarness()`. Anchor each call site
     * with `// @fireweave-flag <key>`.
     */
    public static boolean fwFlag(String key, boolean defaultValue, String targetingKey) {
        return OpenFeatureAPI.getInstance().getClient()
                .getBooleanValue(key, defaultValue, new MutableContext(targetingKey));
    }

    private FwHarness() {
    }
}
