package fireweave; // REPLACED at init: `<app base package>.fireweave` — must match FwHarness.

/*
 * FwProviders.java — scaffolded by `/fireweave:initialise` (JAVA surface).
 *
 * `makeConnectedVendorProvider()` is the prod control-point client with a
 * CONCRETE body: it resolves `FW_API_URL` + `FW_PROJECT_API_KEY` from the
 * process environment and hands them to `Fireweave.init(...)` from the
 * `ai.fireweave` SDK, which brings up the remote adapter against fw-server
 * POST /v1/flags/evaluate (`Authorization: Bearer <FW_PROJECT_API_KEY>`).
 *
 * The SDK reads NO environment itself (spec/modes.md) — this file is the seam
 * where those two vars become explicit options, and it refuses loudly when
 * either is missing rather than allowing a silent all-defaults evaluation.
 * Apps do NOT embed vendor keys — which backend fw-server forwards to is
 * fw-server's concern.
 *
 * `mode` is REQUIRED and never inferred (spec/modes.md): a missing credential
 * is a boot error, never a silent fall-back to local evaluation — that failure
 * mode looks like a green boot and a feature that never ramps.
 *
 * `makeDevProvider()` brings the SAME entry point up in LOCAL mode — an
 * in-process seeded map, no network, no credentials. Both tiers therefore
 * share validation, lifecycle gating and context canonicalization, so the
 * harness cannot skew between them.
 *
 * `registerFwTarget()` is the OTHER half of targeting. Rules match on two
 * kinds of property and you need both:
 *
 *   - DURABLE — registered here, once per login / device provisioning: plan,
 *     beta membership, region. Stored server-side, so rules keep matching
 *     without the app resending anything.
 *   - PER-REQUEST — the per-call evaluation context: page, session,
 *     experiment context. Overrides the registered value for that one call.
 *
 * A rule targeting a property that is never registered AND never sent matches
 * nobody, silently. Register the durable facts at sign-in.
 *
 * Requires `ai.fireweave:fireweave-sdk` on the classpath — that artifact
 * alone. `fireweave-openfeature` is GONE: v1 bans an OpenFeature provider
 * outright (spec/control-points.md "Scope of v1").
 *
 * Observability is NOT wired here. FireWeave does not take responsibility for
 * wiring an observability SDK into an app that has not chosen one.
 */

import ai.fireweave.sdk.application.Fireweave;
import ai.fireweave.sdk.application.FireweaveClient;
import ai.fireweave.sdk.application.InitOptions;
import ai.fireweave.sdk.application.RegisterTargetOptions;
import ai.fireweave.sdk.application.RegisterTargetResult;
import ai.fireweave.sdk.domain.FireweaveException;
import ai.fireweave.sdk.domain.JsonValue;
import ai.fireweave.sdk.domain.Mode;
import ai.fireweave.sdk.domain.TargetKind;

import java.net.URI;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Set;

public final class FwProviders {

    // ── Environment-keyed tier model (D26) — GENERATED by `/fireweave:initialise` ──
    // This lives here, not in FwHarness.java, so the file you review stays
    // small. `staging` is a FIRST-CLASS prod-tier environment — it is NEVER
    // silently folded into dev.
    /**
     * env name -> tier profile — regenerated from FireWeave
     * `list_project_environments`. Keep in sync with `.fireweave/project.json`
     * `rolloutReady.environments`. FW_DEFAULT_ENV is the project's
     * `defaultEnvironment` — the row used when nothing is set at runtime.
     * `/fireweave:initialise --reinit` regenerates this map.
     */
    public static final String FW_DEFAULT_ENV = "development";

    private static final Map<String, String> FW_ENV_PROFILES = new LinkedHashMap<>();

    static {
        FW_ENV_PROFILES.put("development", "dev");
        FW_ENV_PROFILES.put("staging", "prod");
        FW_ENV_PROFILES.put("production", "prod");
    }

    // ── Environment source — GENERATED by `/fireweave:initialise` ────────────
    // FireWeave reads THIS project's OWN environment signal — you do NOT need a
    // FireWeave-specific FW_ENV. `/fireweave:initialise` asks how this repo/CI
    // determines its live environment and generates `readEnvSignal` below to
    // read YOUR var (`APP_ENV` / `SPRING_PROFILES_ACTIVE` / a platform var).
    // FW_ENV is retained ONLY as an optional last-resort override. Regenerated
    // on `--reinit` — edit via the skill.
    // fw:env-source
    private static String readEnvSignal() {
        // Default before init tailors it to your platform: common env vars,
        // then the optional FW_ENV override. `/fireweave:initialise` replaces
        // the first read per your answer.
        String v = System.getenv("APP_ENV");
        if (v == null) v = System.getenv("ENVIRONMENT");
        if (v == null) v = System.getenv("ENV");
        if (v == null) v = System.getenv("FW_ENV");
        return v;
    }

    /**
     * Raw signal value -> FireWeave environment NAME (a key of
     * FW_ENV_PROFILES). initialise fills this only when your values differ
     * from the FireWeave names (e.g. {"prod": "production"}). Empty = identity.
     */
    private static final Map<String, String> FW_ENV_ALIASES = new LinkedHashMap<>();
    // ─────────────────────────────────────────────────────────────────────────

    /** Resolve the running environment NAME from the project's own signal. */
    public static String resolveFwEnvName() {
        String raw = readEnvSignal();
        raw = (raw == null || raw.trim().isEmpty()) ? FW_DEFAULT_ENV : raw.trim();
        return FW_ENV_ALIASES.getOrDefault(raw, raw);
    }

    /**
     * Is this process a prod-tier environment? The tier decision FwHarness
     * branches on, and the token `verify_prod_path` greps for.
     *
     * An UNKNOWN environment is never silently folded into dev or prod — it
     * warns, so the operator adds an explicit row rather than discovering the
     * classification from behaviour.
     */
    public static boolean isProd() {
        String name = resolveFwEnvName();
        String profile = FW_ENV_PROFILES.get(name);
        if (profile != null) {
            return "prod".equals(profile);
        }
        System.err.println("[fireweave] environment '" + name
                + "' has no FW_ENV_PROFILES entry; classified as 'dev'. "
                + "Run /fireweave:initialise --reinit or add it to FW_ENV_PROFILES.");
        return false;
    }


    /** Set by whichever factory below initFwHarness() calls — dev and prod both go through it. */
    private static volatile FireweaveClient fwClient;

    /** PROD: Fireweave remote mode -> fw-server POST /v1/flags/evaluate. */
    public static FireweaveClient makeConnectedVendorProvider() throws FireweaveException {
        String apiUrl = trimEnv("FW_API_URL");
        String apiKey = trimEnv("FW_PROJECT_API_KEY");
        if (apiUrl.isEmpty() || apiKey.isEmpty()) {
            throw new IllegalStateException(
                    "[fireweave] prod control points require FW_API_URL and FW_PROJECT_API_KEY "
                            + "in this environment's runtime env");
        }
        FireweaveClient client = Fireweave.init(InitOptions.builder(Mode.REMOTE)
                .apiUrl(apiUrl)
                .apiKey(apiKey)
                .allowedHosts(allowedHostsFor(apiUrl))
                .build());
        fwClient = client;
        return client;
    }

    /** DEV: the SDK's local mode — in-process seeded map, no network. */
    public static FireweaveClient makeDevProvider() throws FireweaveException {
        // Call-site / manifest defaults stay false (RAMP-1). To dogfood a
        // control point ON locally, seed it here — never `fwFlag(key, true, …)`
        // (that same `true` is the prod fallback when the key is missing from
        // the backend):
        //
        //     controlPoints.put("<feature-slug>", true);
        Map<String, Boolean> controlPoints = new LinkedHashMap<>();
        FireweaveClient client = Fireweave.init(InitOptions.builder(Mode.LOCAL)
                .controlPoints(controlPoints)
                .build());
        fwClient = client;
        return client;
    }

    /**
     * Hosts the SDK is permitted to talk to, derived from the URL you configured.
     *
     * REQUIRED for a self-hosted fw-server, not optional hardening.
     * `Fireweave.init` validates apiUrl against a CANONICAL allowlist (the
     * fireweave.ai hosts plus loopback) when allowedHosts is omitted, so a
     * customer-run fw-server on any other hostname fails initialisation with a
     * bare Configuration error that names nothing. Passing the configured host
     * explicitly is what makes self-hosting work; it is still an allowlist, so
     * it stays an SSRF guard.
     */
    private static Set<String> allowedHostsFor(String apiUrl) {
        Set<String> hosts = new LinkedHashSet<>();
        try {
            String host = URI.create(apiUrl).getHost();
            if (host != null) {
                hosts.add(host);
            }
        } catch (IllegalArgumentException ignored) {
            // Fall through to loopback only — init will reject the bad URL loudly.
        }
        hosts.add("localhost");
        hosts.add("127.0.0.1");
        return hosts;
    }

    /**
     * Register a user or device for DURABLE targeting.
     *
     * Call once from your auth filter / sign-in handler, then pass the SAME id
     * as the targeting key in the per-call evaluation context:
     *
     *     registerFwTarget(user.id(), Map.of("plan", JsonValue.of(user.plan())));
     *
     * Resolves rather than throwing — it runs in sign-in paths, where a
     * targeting concern must not break authentication. Both tiers route through
     * the SAME client: prod sends it to fw-server; local records it in-process
     * and traces one `[fireweave:local]` line saying nothing was sent
     * (spec/modes.md). Log a false return — a silently unregistered target is
     * exactly how targeting rules end up matching nobody.
     */
    public static boolean registerFwTarget(String targetingKey, Map<String, JsonValue> properties) {
        FireweaveClient client = fwClient;
        if (client == null) {
            return false;
        }
        RegisterTargetResult result = client.registerTarget(targetingKey,
                RegisterTargetOptions.builder()
                        .kind(TargetKind.USER)
                        .properties(properties == null ? Collections.emptyMap() : properties)
                        .build());
        return result.ok();
    }

    /** The client initFwHarness() brought up — call-sites read control points through it. */
    public static FireweaveClient getFwClient() {
        FireweaveClient client = fwClient;
        if (client == null) {
            throw new IllegalStateException(
                    "[fireweave] getFwClient() called before initFwHarness() ran.");
        }
        return client;
    }

    private static String trimEnv(String name) {
        String v = System.getenv(name);
        return v == null ? "" : v.trim();
    }

    private FwProviders() {
    }
}
